import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Pencil, Plus, Search, Trash2, Package, X } from 'lucide-react'
import { useStore } from '../../app/store-context'
import type { Product } from '../../mocks/products'
import { Button } from '../../components/ui/button'
import { PageHeader, LinkButton } from '../../components/ui/primitives'
import { Overlay } from '../../components/ui/overlay'
import { EmptyState, StateBoundary } from '../../components/feedback/States'
import { delay } from '@/shared/lib/format'
export function ProductsPage() {
 const { products, user, deleteProduct, notify } = useStore(); const [query, setQuery] = useState(''); const [deleting, setDeleting] = useState<Product | null>(null); const [busy, setBusy] = useState(false); const admin = user?.role === 'ADMIN'
 const filtered = products.filter(p => `${p.name} ${p.sku}`.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru').trim()))
 async function remove() { if (!deleting) return; setBusy(true); await delay(450); deleteProduct(deleting.id); setDeleting(null); setBusy(false); notify('Товар удалён из каталога') }
 const actions = (p: Product) => admin ? <div className="row-actions"><Link className="icon-btn" aria-label={`Редактировать ${p.name}`} title="Редактировать" to={`/products/${p.id}/edit`}><Pencil size={16} /></Link><button className="icon-btn danger-text" aria-label={`Удалить ${p.name}`} title="Удалить" onClick={() => setDeleting(p)}><Trash2 size={16} /></button></div> : null
 return <><PageHeader eyebrow="КАТАЛОГ" title="Товары" description="Товары, для которых вы анализируете спрос." actions={admin && <LinkButton to="/products/new"><Plus size={17} />Добавить товар</LinkButton>} /><div className="toolbar"><div className="search-field"><Search size={18} /><label className="sr-only" htmlFor="product-search">Поиск по названию или SKU</label><input id="product-search" placeholder="Поиск по названию или SKU" value={query} onChange={e => setQuery(e.target.value)} />{query && <button className="icon-btn" aria-label="Очистить поиск" onClick={() => setQuery('')}><X size={16} /></button>}</div><span className="muted" role="status">Товаров: {filtered.length}</span></div><StateBoundary emptyTitle="Товары пока не добавлены" emptyDescription={admin ? 'Добавьте первый товар в каталог.' : 'Администратор ещё не добавил товары.'} emptyAction={admin ? <LinkButton to="/products/new">Добавить товар</LinkButton> : undefined}>{filtered.length ? <><div className="table-wrap desktop-table"><table><caption className="sr-only">Каталог товаров</caption><thead><tr><th>Артикул</th><th>Название товара</th><th>Категория</th>{admin && <th className="align-right">Действия</th>}</tr></thead><tbody>{filtered.map(p => <tr key={p.id}><td className="mono muted">{p.sku}</td><td><div className="product-cell"><span className="product-icon"><Package size={18} strokeWidth={1.5} /></span><strong>{p.name}</strong></div></td><td>{p.category}</td>{admin && <td>{actions(p)}</td>}</tr>)}</tbody></table></div><div className="mobile-records">{filtered.map(p => <article className="record-card" key={p.id}><div className="record-heading"><span className="mono muted">{p.sku}</span>{actions(p)}</div><h3>{p.name}</h3><p className="muted">{p.category}</p></article>)}</div><div className="table-footer">Показано {filtered.length} из {products.length} товаров</div></> : <EmptyState title={query ? 'Товары не найдены' : 'Товары пока не добавлены'} description={query ? 'Попробуйте другое название или артикул.' : 'Добавьте первый товар, чтобы начать работу.'} action={query ? <Button variant="secondary" onClick={() => setQuery('')}>Очистить поиск</Button> : admin ? <LinkButton to="/products/new">Добавить товар</LinkButton> : undefined} />}</StateBoundary>{deleting && <Overlay title="Удалить товар?" onClose={() => { if (!busy) setDeleting(null) }}><div className="delete-body"><div className="delete-symbol"><Trash2 size={24} /></div><p>Товар <strong>«{deleting.name}»</strong> будет удалён из каталога.</p><p className="muted">Ранее созданные прогнозы останутся в истории. Восстановить товар можно, добавив его заново.</p></div><div className="dialog-actions"><Button variant="secondary" disabled={busy} onClick={() => setDeleting(null)}>Отмена</Button><Button variant="danger" disabled={busy} onClick={remove}>{busy ? 'Удаляем...' : 'Удалить товар'}</Button></div></Overlay>}</>
}
