import { useState, type FormEvent } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Check } from 'lucide-react'
import { useStore } from '../../app/store-context'
import { Button } from '../../components/ui/button'
import { Field, LinkButton, PageHeader } from '../../components/ui/primitives'
import { ErrorState } from '../../components/feedback/States'
import { delay } from '@/shared/lib/format'
export function ProductForm() {
 const { id } = useParams(); const { products, saveProduct, notify } = useStore(); const product = products.find(p => p.id === id); const navigate = useNavigate()
 const [sku, setSku] = useState(product?.sku ?? ''); const [name, setName] = useState(product?.name ?? ''); const [category, setCategory] = useState(product?.category ?? ''); const [errors, setErrors] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false)
 if (id && !product) return <ErrorState title="Товар не найден" description="Возможно, этот товар был удалён." retry={() => navigate('/products')} />
 async function submit(e: FormEvent) { e.preventDefault(); const next: Record<string, string> = {}; if (!sku.trim()) next.sku = 'Введите артикул'; else if (products.some(p => p.id !== id && p.sku.toLowerCase() === sku.trim().toLowerCase())) next.sku = 'Товар с таким артикулом уже существует'; if (!name.trim()) next.name = 'Введите название'; if (!category.trim()) next.category = 'Укажите категорию'; setErrors(next); if (Object.keys(next).length) { requestAnimationFrame(() => document.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus()); return } setBusy(true); await delay(450); saveProduct({ id: id || crypto.randomUUID(), sku: sku.trim(), name: name.trim(), category: category.trim() }); notify(id ? 'Изменения сохранены' : 'Товар добавлен'); navigate('/products') }
 return <><LinkButton variant="ghost" to="/products"><ArrowLeft size={16} />К товарам</LinkButton><PageHeader eyebrow="КАТАЛОГ / ТОВАР" title={id ? 'Редактирование товара' : 'Новый товар'} description={id ? 'Обновите основную информацию о товаре.' : 'Добавьте товар для анализа продаж и прогнозирования спроса.'} /><div className="form-layout"><form className="product-form" onSubmit={submit} noValidate><Field label="Артикул (SKU)" htmlFor="sku" error={errors.sku} hint="Уникальный код товара в вашей системе"><input id="sku" value={sku} maxLength={40} placeholder="Например, NB-002" onChange={e => setSku(e.target.value)} aria-invalid={!!errors.sku} aria-describedby={errors.sku ? 'sku-error' : 'sku-hint'} /></Field><Field label="Название товара" htmlFor="product-name" error={errors.name}><input id="product-name" value={name} maxLength={120} placeholder="Например, Ноутбук 14″" onChange={e => setName(e.target.value)} aria-invalid={!!errors.name} aria-describedby={errors.name ? 'product-name-error' : undefined} /></Field><Field label="Категория" htmlFor="category" error={errors.category}><input id="category" value={category} maxLength={60} placeholder="Например, Ноутбуки" list="categories" onChange={e => setCategory(e.target.value)} aria-invalid={!!errors.category} aria-describedby={errors.category ? 'category-error' : undefined} /><datalist id="categories">{Array.from(new Set(products.map(p => p.category))).map(c => <option key={c} value={c} />)}</datalist></Field><div className="form-actions"><LinkButton variant="secondary" to="/products">Отмена</LinkButton><Button type="submit" disabled={busy}><Check size={16} />{busy ? 'Сохраняем...' : id ? 'Сохранить изменения' : 'Создать товар'}</Button></div></form><aside className="form-aside"><span className="eyebrow">О ТОВАРЕ</span><h3>Точность начинается<br />с порядка в данных.</h3><p>Артикул связывает товар с историей продаж. Используйте один и тот же код в каталоге и CSV-файле.</p></aside></div></>
}
