import { useState } from 'react'
import { setReducedMotionDemo, useReducedMotionOverride } from '../../hooks/motionPreference'
import { Link } from 'react-router-dom'
import { SlidersHorizontal, X } from 'lucide-react'
import { useStore, type GeneralState, type ForecastOutcome, type CsvOutcome, type Role } from '../../app/store-context'
export function DemoControls() {
 const [open, setOpen] = useState(false); const s = useStore(); const reduced = useReducedMotionOverride()
 if (!import.meta.env.DEV || !s.user) return null
 return <aside className={`demo-controls ${open ? 'is-open' : ''}`} aria-label="Демонстрационные состояния">{open && <div className="demo-panel"><div className="section-heading"><strong>Проверка прототипа</strong><button className="icon-btn" onClick={() => setOpen(false)} aria-label="Закрыть панель"><X size={16} /></button></div><p className="field-hint">Только локальные демонстрационные данные</p><label>Роль<select value={s.user.role} onChange={e => s.setRole(e.target.value as Role)}><option value="USER">Пользователь</option><option value="ADMIN">Администратор</option></select></label><label>Состояние страницы<select value={s.general} onChange={e => s.setGeneral(e.target.value as GeneralState)}><option value="default">Обычное</option><option value="loading">Загрузка</option><option value="empty">Нет данных</option><option value="error">Ошибка</option></select></label><label>Результат прогнозирования<select value={s.forecastOutcome} onChange={e => s.setForecastOutcome(e.target.value as ForecastOutcome)}><option value="success">Успешно</option><option value="insufficient">Недостаточно истории</option><option value="unavailable">Модель недоступна</option></select></label><label>Результат импорта CSV<select value={s.csvOutcome} onChange={e => s.setCsvOutcome(e.target.value as CsvOutcome)}><option value="success">Успешно</option><option value="partial">Частично успешно</option><option value="structure">Неверная структура</option><option value="error">Ошибка</option></select></label><label>Движение<select value={reduced ? "reduce" : "system"} onChange={e => setReducedMotionDemo(e.target.value === "reduce")}><option value="system">Системная настройка</option><option value="reduce">Уменьшенное движение</option></select></label><div className="demo-route-links"><Link to="/403" onClick={() => setOpen(false)}>Проверить 403</Link><Link to="/demo-not-found" onClick={() => setOpen(false)}>Проверить 404</Link></div></div>}<button className="demo-trigger" aria-expanded={open} onClick={() => setOpen(v => !v)}><SlidersHorizontal size={14} />Демо</button></aside>
}
