import { ArrowRight, CalendarDays, Database, Plus, Upload } from 'lucide-react'
import { useStore } from '../../app/store-context'
import { PageHeader, LinkButton, SectionTitle, Badge, OpenLink } from '../../components/ui/primitives'
import { StateBoundary } from '../../components/feedback/States'
import { DepthSurface } from '../../components/ui/DepthSurface'
import { ForecastChart } from '../../components/charts/ForecastChart'
import { ForecastList } from './ForecastList'
import { availability } from '../../mocks/dashboard'
import { date, days, number } from '../../lib/format'
export function Dashboard() {
 const { forecasts, products, user } = useStore(); const latest = forecasts[0]; const data = availability(products.map(p => p.id))
 return <><PageHeader eyebrow="ОБЗОР РАБОЧЕГО ПРОСТРАНСТВА" title="Главная" description="Ваши данные. Следующий шаг — точный прогноз." actions={<LinkButton to="/forecasts/new"><Plus size={17} />Создать прогноз</LinkButton>} /><StateBoundary emptyTitle="Начните с данных" emptyDescription={user?.role === 'ADMIN' ? 'Добавьте товары и импортируйте историю продаж.' : 'Пока нет данных для прогнозирования. Обратитесь к администратору.'} emptyAction={user?.role === 'ADMIN' ? <LinkButton to="/sales/import">Импорт CSV</LinkButton> : undefined}><div className="dashboard-composition"><DepthSurface className="latest-forecast"><div className="section-heading"><span className="eyebrow">ПОСЛЕДНИЙ ПРОГНОЗ</span><Badge /></div><div className="latest-title"><h2>{latest.product.name}</h2><span className="mono muted">{latest.product.sku}</span></div><div className="inline-meta"><span><CalendarDays size={14} />{date(latest.createdAt)}</span><span>Горизонт · {days(latest.horizon)}</span></div><ForecastChart forecast={latest} compact /><div className="latest-bottom"><span className="muted">История продаж и ожидаемый спрос</span><OpenLink to={`/forecasts/${latest.id}`} label="Открыть прогноз" /></div></DepthSurface><aside className="availability"><div className="section-heading"><span className="eyebrow">ДОСТУПНОСТЬ ДАННЫХ</span><Database size={18} /></div><div className="availability-count"><strong>{number(products.length)}</strong><span>товаров в каталоге</span></div><div className="availability-detail"><span>Записи о продажах</span><strong>{number(data.count)}<small> наблюдений</small></strong></div><div className="availability-detail"><span>Период истории</span><strong className="date-range">{data.from ? date(data.from) : '—'}<span>—</span>{data.to ? date(data.to) : '—'}</strong></div><div className="availability-note"><span className="status-dot" />История доступна для прогнозирования</div><LinkButton variant="ghost" to="/sales">Посмотреть продажи<ArrowRight size={16} /></LinkButton>{user?.role === 'ADMIN' && <LinkButton variant="secondary" to="/sales/import"><Upload size={16} />Импорт CSV</LinkButton>}</aside></div><section className="recent-section"><SectionTitle aside={<OpenLink to="/forecasts" label="Вся история" />}>Недавние прогнозы <span className="count-label">{forecasts.length}</span></SectionTitle><ForecastList forecasts={forecasts.slice(0, 4)} compact /></section></StateBoundary></>
}
