import { useEffect, useRef, useState, type FormEvent } from 'react'
import { useLocation, useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, ArrowRight, CalendarDays, Check, Info, Plus, Search } from 'lucide-react'
import { useStore } from '../../app/store-context'
import { mockForecast } from '../../mocks/forecasts'
import { salesFor } from '../../mocks/sales'
import { PageHeader, LinkButton, Field, Badge, SectionTitle } from '../../components/ui/primitives'
import { Button } from '../../components/ui/button'
import { EmptyState, Signal, StateBoundary } from '../../components/feedback/States'
import { SignalCore } from '../../components/signal/SignalCore'
import { ForecastChart } from '../../components/charts/ForecastChart'
import { ForecastList } from './ForecastList'
import { date, days, number } from '@/shared/lib/format'
export function ForecastCreate() {
 const { products, forecastOutcome, addForecast, general } = useStore(); const navigate = useNavigate(); const [productId, setProductId] = useState(''); const [horizon, setHorizon] = useState('14'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [fieldError, setFieldError] = useState(''); const timer = useRef<ReturnType<typeof setTimeout> | null>(null)
 useEffect(() => () => { if (timer.current) clearTimeout(timer.current) }, [])
 const product = products.find(p => p.id === productId); const history = salesFor(productId)
 function submit(e: FormEvent) { e.preventDefault(); if (!product) { setFieldError('Выберите товар для прогнозирования'); document.getElementById('forecast-product')?.focus(); return } setError(''); setFieldError(''); setBusy(true); timer.current = setTimeout(() => { if (forecastOutcome === 'insufficient' || !history.length) { setError('Недостаточно истории продаж. Для выбранного товара нужны исторические наблюдения.'); setBusy(false); return } if (forecastOutcome === 'unavailable') { setError('Модель прогнозирования сейчас недоступна. Попробуйте построить прогноз ещё раз.'); setBusy(false); return } const f = mockForecast(product, Number(horizon)); addForecast(f); navigate(`/forecasts/${f.id}`, { state: { reveal: true } }) }, 2200) }
 return <><PageHeader eyebrow="ОТ ИСТОРИИ К ПРОГНОЗУ" title="Новый прогноз" description="Выберите товар и период, на который хотите оценить спрос." /><StateBoundary emptyTitle="Нет товаров для прогноза" emptyDescription="Добавьте товары и историю продаж перед созданием прогноза."><div className="forecast-create-grid"><div className="forecast-form-panel">{busy ? <div className="forecast-processing" aria-busy="true"><SignalCore processing /><span className="eyebrow">ПРОГНОЗ СПРОСА</span><h2>{product?.name}</h2><p className="muted">{product?.sku} · {days(Number(horizon))}</p><Signal /><p className="processing-note">Результат появится здесь через несколько секунд.</p></div> : <form onSubmit={submit} noValidate><div className="form-section-title"><span className="step-number">01</span><div><h2>Параметры прогноза</h2><p>Два параметра — один ясный результат.</p></div></div><Field label="Товар" htmlFor="forecast-product" error={fieldError}><select id="forecast-product" value={productId} onChange={e => { setProductId(e.target.value); setError(''); setFieldError('') }} aria-invalid={!!fieldError} aria-describedby={fieldError ? 'forecast-product-error' : undefined}><option value="">Выберите товар</option>{products.map(p => <option value={p.id} key={p.id}>{p.name} · {p.sku}</option>)}</select></Field><Field label="Горизонт прогнозирования" htmlFor="horizon" hint="Количество дней после последней даты в истории продаж"><select id="horizon" value={horizon} onChange={e => setHorizon(e.target.value)}>{[7, 14, 30].map(n => <option key={n} value={n}>{days(n)}</option>)}</select></Field>{product && <div className="history-context"><div><CalendarDays size={17} /><strong>История выбранного товара</strong></div>{history.length ? <dl><div><dt>Период</dt><dd>{date(history[0].date)} — {date(history.at(-1)!.date)}</dd></div><div><dt>Наблюдений</dt><dd>{number(history.length)}</dd></div></dl> : <p>История продаж пока отсутствует.</p>}</div>}{error && <div className="inline-error" role="alert"><Info size={18} /><span>{error}</span></div>}<Button type="submit" className="full-width" disabled={!products.length || general !== 'default'}>Построить прогноз<ArrowRight size={17} /></Button></form>}</div><aside className="forecast-explainer"><span className="eyebrow">ЧТО ВЫ ПОЛУЧИТЕ</span><h2>История.<br />Продолжение.<br /><span>Понимание спроса.</span></h2><ul><li><Check size={16} />Исторические продажи и прогноз на одном графике</li><li><Check size={16} />Показатели ошибки: MAE, RMSE и MAPE</li><li><Check size={16} />Значения спроса на каждый день</li></ul><div className="plain-note"><Info size={17} /><p>Прототип использует подготовленные примеры. Результат не является реальным прогнозом.</p></div></aside></div></StateBoundary></>
}
export function ForecastResult() {
 const { id } = useParams(); const { forecasts } = useStore(); const location = useLocation(); const [reveal] = useState(!!location.state?.reveal); const f = forecasts.find(f => f.id === id)
 useEffect(() => { if (location.state?.reveal) window.history.replaceState({ ...window.history.state, usr: null }, '') }, [location.state])
 if (!f) return <><PageHeader title="Прогноз не найден" /><EmptyState title="Этот прогноз недоступен" description="Откройте другой прогноз из истории." action={<LinkButton to="/forecasts">К истории</LinkButton>} /></>
 return <div className={reveal ? 'forecast-result is-new-result' : 'forecast-result'}><div className="result-back"><LinkButton variant="ghost" to="/forecasts"><ArrowLeft size={15} />К истории</LinkButton><Badge /></div><PageHeader eyebrow={`РЕЗУЛЬТАТ ПРОГНОЗА / ${f.product.sku}`} title={f.product.name} actions={<LinkButton variant="secondary" to="/forecasts/new"><Plus size={17} />Новый прогноз</LinkButton>} /><div className="result-context"><div><span>Горизонт</span><strong>{days(f.horizon)}</strong></div><div><span>Период прогноза</span><strong>{date(f.values[0].date)} — {date(f.values.at(-1)!.date)}</strong></div><div><span>Создан</span><strong>{date(f.createdAt)} · {date(f.createdAt, { hour: '2-digit', minute: '2-digit' })}</strong></div></div><StateBoundary emptyTitle="Нет значений прогноза" emptyDescription="Создайте новый прогноз для выбранного товара."><section className={`result-chart-section ${reveal ? 'result-reveal' : ''}`}><SectionTitle aside={<span className="muted">Ежедневный спрос</span>}>От истории — к следующему периоду</SectionTitle><ForecastChart forecast={f} reveal={reveal} /></section><div className="metric-strip"><div><span>MAE <small>Средняя абсолютная ошибка</small></span><strong>{number(f.mae, 2)}<small> шт.</small></strong></div><div><span>RMSE <small>Среднеквадратическая ошибка</small></span><strong>{number(f.rmse, 2)}<small> шт.</small></strong></div><div><span>MAPE <small>Средняя процентная ошибка</small></span><strong>{number(f.mape, 2)}<small> %</small></strong></div></div><p className="metric-note"><Info size={14} />Демонстрационные метрики на истории за 18–31 августа 2026. Не отражают точность будущих продаж.</p><section className="forecast-values"><SectionTitle aside={<span className="muted">{f.values.length} значений</span>}>Прогноз по дням</SectionTitle><div className="desktop-table table-wrap"><table><caption className="sr-only">Прогнозные значения спроса</caption><thead><tr><th>Дата</th><th>Товар</th><th className="numeric">Прогноз спроса, шт.</th></tr></thead><tbody>{f.values.map(v => <tr key={v.date}><td>{date(v.date)}</td><td>{f.product.name}</td><td className="numeric forecast-number">{number(v.value)}</td></tr>)}</tbody></table></div><div className="mobile-records forecast-value-cards">{f.values.map(v => <div className="record-card" key={v.date}><span>{date(v.date)}</span><strong className="forecast-number">{number(v.value)} шт.</strong></div>)}</div></section></StateBoundary></div>
}
export function ForecastHistory() {
 const { forecasts } = useStore(); const [query, setQuery] = useState(''); const filtered = forecasts.filter(f => `${f.product.name} ${f.product.sku}`.toLowerCase().includes(query.trim().toLowerCase()))
 return <><PageHeader eyebrow="СОХРАНЁННЫЕ РЕЗУЛЬТАТЫ" title="История прогнозов" description="Вернитесь к любому ранее созданному прогнозу." actions={<LinkButton to="/forecasts/new"><Plus size={16} />Создать прогноз</LinkButton>} /><div className="toolbar"><div className="search-field"><Search size={18} /><label className="sr-only" htmlFor="forecast-search">Поиск по товару или SKU</label><input id="forecast-search" placeholder="Поиск по товару или SKU" value={query} onChange={e => setQuery(e.target.value)} /></div><span className="muted" role="status">Прогнозов: {filtered.length}</span></div><StateBoundary emptyTitle="Прогнозы ещё не создавались" emptyDescription="Создайте первый прогноз, чтобы он появился в истории." emptyAction={<LinkButton to="/forecasts/new">Создать прогноз</LinkButton>}>{filtered.length ? <ForecastList forecasts={filtered} /> : <EmptyState title="Прогнозы не найдены" description="Попробуйте другое название товара или артикул." action={<Button variant="secondary" onClick={() => setQuery('')}>Очистить поиск</Button>} />}</StateBoundary></>
}
export function RouteError({ forbidden = false }: { forbidden?: boolean }) { return <div className="route-error"><span className="error-code">{forbidden ? '403' : '404'}</span><PageHeader title={forbidden ? 'Доступ ограничен' : 'Страница не найдена'} description={forbidden ? 'Этот раздел доступен только администратору.' : 'Возможно, адрес изменился или в нём допущена ошибка.'} /><LinkButton to="/dashboard"><ArrowLeft size={16} />На главную</LinkButton></div> }
