import type { ReactNode } from 'react'
import { AlertCircle, Database, RefreshCw } from 'lucide-react'
import { Button } from '../ui/button'
import { useStore } from '../../app/store-context'
export function EmptyState({ title = 'Пока нет данных', description = 'Здесь появятся данные, когда они будут доступны.', action }: { title?: string; description?: string; action?: ReactNode }) { return <div className="empty-state"><div className="state-icon"><Database size={23} strokeWidth={1.5} /></div><h2>{title}</h2><p>{description}</p>{action}</div> }
export function ErrorState({ title = 'Не удалось загрузить данные', description = 'Попробуйте ещё раз. Введённые данные сохранены.', retry }: { title?: string; description?: string; retry?: () => void }) { return <div className="empty-state error-state" role="alert"><div className="state-icon"><AlertCircle size={23} /></div><h2>{title}</h2><p>{description}</p>{retry && <Button variant="secondary" onClick={retry}><RefreshCw size={16} />Повторить</Button>}</div> }
export function Skeleton() { return <div className="skeleton-page" role="status" aria-label="Загружаем данные"><div className="skeleton skeleton-title" /><div className="skeleton skeleton-chart" />{[0, 1, 2, 3].map(i => <div className="skeleton skeleton-row" key={i} />)}<span className="sr-only">Загружаем данные...</span></div> }
export function StateBoundary({ children, emptyTitle, emptyDescription, emptyAction }: { children: ReactNode; emptyTitle?: string; emptyDescription?: string; emptyAction?: ReactNode }) { const { general, setGeneral } = useStore(); return general === 'loading' ? <Skeleton /> : general === 'error' ? <ErrorState retry={() => setGeneral('default')} /> : general === 'empty' ? <EmptyState title={emptyTitle} description={emptyDescription} action={emptyAction} /> : children }
export function Signal({ text = 'Формируем прогноз...' }: { text?: string }) { return <div className="signal-status" role="status"><div className="signal-track" aria-hidden="true"><span /></div><span>{text}</span></div> }
