CREATE TABLE departments (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             name VARCHAR(150) NOT NULL,

                             is_active BOOLEAN NOT NULL DEFAULT TRUE,

                             created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                             updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                             CONSTRAINT departments_name_not_blank
                                 CHECK (BTRIM(name) <> '')
);

CREATE UNIQUE INDEX departments_name_uq
    ON departments (LOWER(name));