CREATE TABLE positions (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           department_id BIGINT NOT NULL,

                           name VARCHAR(150) NOT NULL,

                           is_active BOOLEAN NOT NULL DEFAULT TRUE,

                           created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT positions_department_fk
                               FOREIGN KEY (department_id)
                                   REFERENCES departments(id)
                                   ON DELETE RESTRICT,

                           CONSTRAINT positions_name_not_blank
                               CHECK (BTRIM(name) <> '')
);

CREATE UNIQUE INDEX positions_department_name_uq
    ON positions (
                  department_id,
                  LOWER(BTRIM(name))
        );

CREATE INDEX positions_department_active_idx
    ON positions (
                  department_id,
                  is_active
        );