CREATE TABLE forecasts (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           user_id BIGINT NOT NULL,

                           product_id BIGINT NOT NULL,

                           forecast_horizon INTEGER NOT NULL,

                           model_version VARCHAR(100) NOT NULL,

                           status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

                           mae NUMERIC(18, 6),

                           rmse NUMERIC(18, 6),

                           mape NUMERIC(18, 6),

                           created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           started_at TIMESTAMPTZ,

                           completed_at TIMESTAMPTZ,

                           error_message VARCHAR(1000),

                           CONSTRAINT forecasts_user_fk
                               FOREIGN KEY (user_id)
                                   REFERENCES users(id)
                                   ON DELETE RESTRICT,

                           CONSTRAINT forecasts_product_fk
                               FOREIGN KEY (product_id)
                                   REFERENCES products(id)
                                   ON DELETE RESTRICT,

                           CONSTRAINT forecasts_horizon_positive
                               CHECK (forecast_horizon > 0),

                           CONSTRAINT forecasts_model_version_not_blank
                               CHECK (BTRIM(model_version) <> ''),

                           CONSTRAINT forecasts_status_check
                               CHECK (
                                   status IN (
                                              'PENDING',
                                              'PROCESSING',
                                              'COMPLETED',
                                              'FAILED'
                                       )
                                   ),

                           CONSTRAINT forecasts_mae_non_negative
                               CHECK (
                                   mae IS NULL
                                       OR mae >= 0
                                   ),

                           CONSTRAINT forecasts_rmse_non_negative
                               CHECK (
                                   rmse IS NULL
                                       OR rmse >= 0
                                   ),

                           CONSTRAINT forecasts_mape_non_negative
                               CHECK (
                                   mape IS NULL
                                       OR mape >= 0
                                   )
);

CREATE INDEX forecasts_user_created_idx
    ON forecasts (
                  user_id,
                  created_at DESC
        );

CREATE INDEX forecasts_product_created_idx
    ON forecasts (
                  product_id,
                  created_at DESC
        );

CREATE INDEX forecasts_status_idx
    ON forecasts (
                  status
        );