CREATE TABLE forecast_values (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                 forecast_id BIGINT NOT NULL,

                                 forecast_date DATE NOT NULL,

                                 predicted_quantity NUMERIC(18, 4) NOT NULL,

                                 CONSTRAINT forecast_values_forecast_fk
                                     FOREIGN KEY (forecast_id)
                                         REFERENCES forecasts(id)
                                         ON DELETE CASCADE,

                                 CONSTRAINT forecast_values_quantity_non_negative
                                     CHECK (predicted_quantity >= 0),

                                 CONSTRAINT forecast_values_forecast_date_uq
                                     UNIQUE (
                                             forecast_id,
                                             forecast_date
                                         )
);